---
- name: Clean build_dir
  file:
    state: absent
    path: "{{ build_dir }}/"
  tags: setup

- name: Build build_dir
  file:
    state: directory
    path: "{{ build_dir }}/"
  tags: setup

- name: check out a git repository
  local_action:
    module: git
    repo: "{{ git_source_repository_path }}"
    dest: "{{ build_dir }}"
    version: "{{ branch }}"
    accept_hostkey: true
  tags: checkout

- include: "{{ hook_build_tasks | default(lookup('pipe', 'pwd') ~ '/../hooks/empty.yml') }}"

- name: git add remote repository "{{ git_target_repository_path }}"
  command: git remote add remote "{{ git_target_repository_path }}" warn=no
  args:
    warn: false
    chdir: "{{ build_dir }}"
  tags: prepare_commit

- name: Configure gitignore
  blockinfile:
    path: "{{ build_dir }}/.gitignore"
    marker: "#### {mark} COMPOSER ###"
    content: ""
  tags: prepare_commit

- name: Remove all git folders without the root .git directory
  command: "ls | xargs find 2>/dev/null | egrep /\.git$ | xargs rm -rf"
  args:
    chdir: "{{ build_dir }}"
  tags: prepare_commit

- name: git add files
  command: git add .
  args:
    chdir: "{{ build_dir }}"
  tags: prepare_commit

- name: git commit files
  command: "git commit -am \"Build: {{ ansible_date_time.iso8601 }}\""
  args:
    chdir: "{{ build_dir }}"
  tags: commit

- name: git push
  command: "git push --force remote {{ branch }}:{{ branch }}-build"
  args:
    chdir: "{{ build_dir }}"
  tags: push