---
- block:
  - name: Create build_dir
    file:
      state: directory
      path: "{{ checkout_dir }}"
    tags: setup

  - name: Check out git repository
    local_action:
      module: git
      repo: "{{ git_source_repository_path }}"
      dest: "{{ checkout_dir }}"
      version: "{{ branch }}"
      accept_hostkey: true
    tags: checkout

  - include: "{{ hook_build_tasks | default(lookup('pipe', 'pwd') ~ '/../hooks/empty.yml') }}"

  - name: Clean push_dir
    file:
      state: absent
      path: "{{ push_dir }}"
    tags: prepare_commit

  - name: Copy to push directory
    synchronize:
      mode: "pull"
      src: "{{ checkout_dir }}"
      dest: "{{ build_dir }}/push"

  - name: Find all gitignores
    shell: "find 2>/dev/null | egrep /\\.gitignore$"
    args:
      chdir: "{{ push_dir }}"
    register: gitignore_to_check
    ignore_errors: yes
    tags: prepare_commit

  - name: Remove markers in gitignore "#### BEGIN REMOVE ANDOCK-CI ..."
    blockinfile:
      path: "{{ push_dir }}/{{ item }}"
      marker: "#### {mark} REMOVE ANDOCK-CI ###"
      content: ""
    with_items: "{{ gitignore_to_check.stdout_lines }}"
    tags: prepare_commit

  - name: Git add remote repository "{{ git_target_repository_path }}"
    command: git remote add remote "{{ git_target_repository_path }}" warn=no
    args:
      warn: false
      chdir: "{{ push_dir }}"
    tags: prepare_commit

  - name: Remove all git folders without the root .git directory
    shell: "ls | xargs find 2>/dev/null | egrep /\\.git$ | xargs rm -rf"
    args:
      chdir: "{{ push_dir }}"
    tags: prepare_commit

  - name: Add files
    command: git add .
    args:
      chdir: "{{ push_dir }}"
    tags: prepare_commit

  - name: Commit files
    command: "git commit -am \"Build: {{ ansible_date_time.iso8601 }}\""
    args:
      chdir: "{{ push_dir }}"
    tags: commit

  - name: BAAAM! Push it
    command: "git push --force remote {{ branch }}:{{ branch }}-build"
    args:
      chdir: "{{ push_dir }}"
    tags: push

- rescue:
  - name: Build failed. Clean up build dir. Restart your build to checkout again.
    file:
      state: absent
      path: "{{ build_dir }}"