---
- block:
  - name: "Create build directory"
    file:
      state: directory
      path: "{{ checkout_path }}"
    tags: setup

  - name: "Clone or pull repository"
    git:
      repo: "{{ git_source_repository_path }}"
      dest: "{{ checkout_path }}"
      version: "{{ branch }}"
      accept_hostkey: true
      force: yes
    tags: checkout
    when: git_source_repository_path is defined

  - include: "{{ hook_build_tasks | default(role_path ~ '/hooks/empty.yml') }}"

  - name: "Remove old push directory. (If one exists)"
    file:
      state: absent
      path: "{{ push_path }}"

  - name: "Copy to push directory"
    command: "rsync -a {{ checkout_path }}/ {{ push_path }} --exclude {{ push_path }}"

  - name: "Prepare commit: Register gitignores"
    shell: "find 2>/dev/null | egrep /\\.gitignore$"
    args:
      chdir: "{{ push_path }}"
    register: gitignore_to_check
    ignore_errors: yes
    tags: prepare_commit

  - name: "Prepare commit: Remove marker in gitignore \"#### BEGIN REMOVE ANDOCK-CI ...\""
    blockinfile:
      path: "{{ push_path }}/{{ item }}"
      marker: "#### {mark} REMOVE ANDOCK-CI ###"
      content: ""
    with_items: "{{ gitignore_to_check.stdout_lines }}"
    tags: prepare_commit
    no_log: true

  - name: "Prepare commit: Add git remote \"{{ git_target_repository_path }}\""
    command: git remote add remote "{{ git_target_repository_path }}" warn=no
    args:
      warn: false
      chdir: "{{ push_path }}"
    tags: prepare_commit

  - name: "Prepare commit: Remove all git folders without the root .git directory"
    shell: "ls | xargs find 2>/dev/null | egrep /\\.git$ | xargs rm -rf"
    args:
      chdir: "{{ push_path }}"
    tags: prepare_commit

  - name: "Prepare commit: git add ."
    command: git add .
    args:
      chdir: "{{ push_path }}"
    tags: prepare_commit

  - name: "Prepare commit: git config user.name"
    shell: git config user.name $(git --no-pager show -s --format='%an' HEAD)
    args:
      chdir: "{{ push_path }}"
    tags: prepare_commit

  - name: "Prepare commit: git config user.email"
    shell: git config user.email $(git --no-pager show -s --format='%ae' HEAD)
    args:
      chdir: "{{ push_path }}"
    tags: prepare_commit

  - name: "Commit files"
    shell: "git commit --allow-empty -am \"Build: {{ ansible_date_time.iso8601 }}\""
    args:
      chdir: "{{ push_path }}"
    tags: commit

  - name: "BAAAM! Push it"
    command: "git push --force remote {{ branch }}:{{ target_branch }}"
    args:
      chdir: "{{ push_path }}"
    tags: push

  always:
    - name: "Prepare clean up"
      file: dest="{{ push_path }}" mode=777  recurse=yes

    - name: "Clean up: Remove push directory"
      file:
        state: absent
        path: "{{ push_path }}"
